"""
Outline_NETWORKING_AGENT: Networking Strategy Compiler

Loads networking research and compiles it into a 3-slide strategy outline
with exactly 3 bullets per slide.
"""

import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Any
from dotenv import load_dotenv

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage

env_path = Path(__file__).parent.parent.parent / "Secrets" / ".env"
load_dotenv(env_path)


class OutlineNetworkingAgent:
    """Agent for compiling networking research into a 3-slide outline."""

    def __init__(self, api_key: str = None):
        self.openai_api_key = api_key or os.getenv("OPENAI_API_KEY")

        if not self.openai_api_key:
            raise ValueError("OpenAI API key not provided")

        self.llm = ChatOpenAI(
            model="gpt-4o-mini",
            temperature=0.4,
            openai_api_key=self.openai_api_key
        )

        self.base_path = Path(__file__).parent.parent.parent
        self.outputs_path = self.base_path / "Outputs"
        self.outputs_path.mkdir(exist_ok=True)

    def load_research(self, sector: str) -> str:
        """Load the latest networking research file for the sector."""
        sector_slug = sector.lower().replace(" ", "_")
        pattern = f"networking_research_{sector_slug}_*.md"
        matching_files = list(self.outputs_path.glob(pattern))

        if not matching_files:
            raise FileNotFoundError("No networking research found. Run NetworkingResearch_Agent first.")

        latest_file = max(matching_files, key=lambda p: p.stat().st_mtime)
        print(f"Loaded: {latest_file.name}")

        with open(latest_file, 'r', encoding='utf-8') as f:
            return f.read()

    def compile_strategy(self, sector: str, region: str, research: str) -> str:
        """Compile networking research into a 3-slide outline."""
        system_prompt = """You are a VC platform strategist building a networking strategy deck.
Create EXACTLY 3 slides with EXACTLY 3 bullets each.
Preserve any citations/URLs from the research when possible.
Keep bullets concise (under 100 characters)."""

        user_prompt = f"""Create a networking strategy outline for {sector} ({region}) using the research below.

{research}

Return ONLY markdown in this structure:

## 1. Target Profiles
- Bullet 1
- Bullet 2
- Bullet 3

## 2. Outreach Methods
- Bullet 1
- Bullet 2
- Bullet 3

## 3. Ethical Norms & Reputation
- Bullet 1
- Bullet 2
- Bullet 3

Rules:
- Exactly 3 bullets per section
- Preserve citations if present
- Do not add new research"""

        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt)
        ]

        response = self.llm.invoke(messages)
        return response.content

    def format_final_doc(self, sector: str, region: str, strategy_content: str) -> str:
        """Format the final networking strategy document."""
        timestamp = datetime.now().strftime("%B %d, %Y")

        return f"""# Networking Strategy Deck
## {sector}

**Region**: {region}
**Date**: {timestamp}
**Generated by**: GPTOSS VC Thesis Agents

---

{strategy_content}

---

## Methodology

This strategy was generated using a dedicated networking workflow:
- **NetworkingResearch_Agent**: Target profiles, outreach methods, ethics
- **Outline_NETWORKING_AGENT**: Research compilation and slide outline

---

*Generated by GPTOSS VC Thesis System*
"""

    def save_strategy(self, sector: str, strategy: str) -> Path:
        """Save the completed networking strategy outline."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        sector_slug = sector.lower().replace(" ", "_")
        filename = f"networking_strategy_{sector_slug}_{timestamp}.md"

        output_path = self.outputs_path / filename
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(strategy)

        print(f"\n[OK] Strategy saved to: {output_path}")
        return output_path

    def run(self, sector: str, region: str = "US") -> Path:
        """Run the networking outline workflow."""
        print(f"\n{'='*60}")
        print("Outline_NETWORKING_AGENT: Compiling Networking Strategy")
        print(f"Sector: {sector}")
        print(f"Region: {region}")
        print(f"{'='*60}\n")

        research = self.load_research(sector)
        print("\nCompiling strategy...")
        strategy_content = self.compile_strategy(sector, region, research)

        print("Formatting final document...")
        final_doc = self.format_final_doc(sector, region, strategy_content)

        output_path = self.save_strategy(sector, final_doc)

        print(f"\n{'='*60}")
        print("[OK] Networking strategy compilation complete!")
        print(f"{'='*60}\n")

        return output_path


def main():
    """CLI entry point for Outline_NETWORKING_AGENT."""
    if len(sys.argv) < 2:
        print("Usage: python agent.py <sector> [region]")
        print("Example: python agent.py 'B2B Fintech' 'US'")
        sys.exit(1)

    sector = sys.argv[1]
    region = sys.argv[2] if len(sys.argv) > 2 else "US"

    try:
        agent = OutlineNetworkingAgent()
        agent.run(sector, region)
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
