"""
Outline_AGENT_VC: Thesis Compiler

Pulls industry research from Slide 1-5 agents, populates outline with data,
and generates a complete VC thesis markdown document.
"""

import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any
import re
from dotenv import load_dotenv

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage

env_path = Path(__file__).parent.parent.parent / "Secrets" / ".env"
load_dotenv(env_path)


class OutlineAgent:
    """Agent for compiling research into a complete VC thesis."""

    def __init__(self, api_key: str = None, langchain_api_key: str = None):
        """Initialize the Outline Agent."""
        self.openai_api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.langchain_api_key = langchain_api_key or os.getenv("LANGCHAIN_API_KEY")

        if not self.openai_api_key:
            raise ValueError("OpenAI API key not provided")

        self.llm = ChatOpenAI(
            model="gpt-4o-mini",
            temperature=0.5,
            openai_api_key=self.openai_api_key
        )

        self.base_path = Path(__file__).parent.parent.parent
        self.outputs_path = self.base_path / "Outputs"
        self.outputs_path.mkdir(exist_ok=True)

    def load_slide_research(self, sector: str) -> Dict[str, str]:
        """
        Load research from all slide agents.

        Args:
            sector: The sector to search for

        Returns:
            Dict mapping slide number to research content
        """
        sector_slug = sector.lower().replace(" ", "_")
        slides = {}

        for slide_num in range(1, 6):
            # Find the most recent file for this slide and sector
            pattern = f"slide{slide_num}_{sector_slug}_*.md"
            matching_files = list(self.outputs_path.glob(pattern))

            if matching_files:
                # Sort by modification time and get most recent
                latest_file = max(matching_files, key=lambda p: p.stat().st_mtime)
                with open(latest_file, 'r', encoding='utf-8') as f:
                    slides[f"slide{slide_num}"] = f.read()
                print(f"Loaded: {latest_file.name}")
            else:
                print(f"Warning: No research found for Slide {slide_num}")
                slides[f"slide{slide_num}"] = f"[No research available for Slide {slide_num}]"

        return slides

    def compile_thesis(self, sector: str, region: str, slides: Dict[str, str]) -> str:
        """
        Compile all slide research into a cohesive thesis.

        Args:
            sector: Industry sector
            region: Geographic region
            slides: Dict of slide research content

        Returns:
            Complete thesis markdown
        """
        system_prompt = """You are a venture capital thesis writer compiling research into a polished document.
Your task is to take research from 5 slides and create a cohesive, well-structured VC industry thesis.

The output should be:
- Professional and polished
- Well-formatted markdown
- Cohesive narrative flow
- Properly cited
- Ready to present to partners

Do not add significant new research. Focus on organizing and presenting the existing research effectively."""

        user_prompt = f"""Compile a complete VC industry thesis for {sector} ({region}) using the following research:

{slides.get('slide1', '')}

---

{slides.get('slide2', '')}

---

{slides.get('slide3', '')}

---

{slides.get('slide4', '')}

---

{slides.get('slide5', '')}

---

Create a complete, polished markdown document with:
1. Executive summary
2. All 5 slides' content properly organized
3. Smooth transitions between sections
4. Consistent formatting
5. Citations preserved
6. Professional tone throughout

The document should tell a complete story from market trends through to candidate companies."""

        messages = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt)
        ]

        response = self.llm.invoke(messages)
        return response.content

    def format_final_thesis(self, sector: str, region: str, thesis_content: str) -> str:
        """
        Format the final thesis document.

        Args:
            sector: Industry sector
            region: Geographic region
            thesis_content: Compiled thesis content

        Returns:
            Final formatted thesis
        """
        timestamp = datetime.now().strftime("%B %d, %Y")

        final_doc = f"""# Venture Capital Industry Thesis
## {sector}

**Region**: {region}
**Date**: {timestamp}
**Generated by**: GPTOSS VC Thesis Agents

---

{thesis_content}

---

## Methodology

This thesis was generated using a multi-agent research system:
- **Slide1_Agent**: Market trends and inflection points
- **Slide2_Agent**: Ecosystem taxonomy mapping
- **Slide3_Agent**: Macro-market thesis development
- **Slide4_Agent**: Investment filter definition
- **Slide5_Agent**: Company candidate identification
- **Outline_AGENT_VC**: Research compilation and synthesis

For questions or updates, re-run the agent pipeline with updated parameters.

---

*Generated by GPTOSS VC Thesis System*
"""
        return final_doc

    def save_thesis(self, sector: str, thesis: str) -> Path:
        """Save the completed thesis."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        sector_slug = sector.lower().replace(" ", "_")
        filename = f"vc_thesis_{sector_slug}_{timestamp}.md"

        output_path = self.outputs_path / filename

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(thesis)

        print(f"\n[OK] Thesis saved to: {output_path}")
        return output_path

    def run(self, sector: str, region: str = "US") -> Path:
        """
        Run the complete thesis compilation workflow.

        Args:
            sector: Industry sector
            region: Geographic region

        Returns:
            Path to final thesis document
        """
        print(f"\n{'='*60}")
        print(f"Outline_AGENT_VC: Compiling VC Thesis")
        print(f"Sector: {sector}")
        print(f"Region: {region}")
        print(f"{'='*60}\n")

        # Load all slide research
        print("Loading research from slide agents...")
        slides = self.load_slide_research(sector)

        # Compile into thesis
        print("\nCompiling thesis...")
        thesis_content = self.compile_thesis(sector, region, slides)

        # Format final document
        print("Formatting final document...")
        final_thesis = self.format_final_thesis(sector, region, thesis_content)

        # Save
        output_path = self.save_thesis(sector, final_thesis)

        print(f"\n{'='*60}")
        print(f"[OK] Thesis compilation complete!")
        print(f"{'='*60}\n")

        return output_path


def main():
    """CLI entry point for Outline_AGENT_VC."""
    if len(sys.argv) < 2:
        print("Usage: python agent.py <sector> [region]")
        print("Example: python agent.py 'B2B Fintech' 'US'")
        sys.exit(1)

    sector = sys.argv[1]
    region = sys.argv[2] if len(sys.argv) > 2 else "US"

    try:
        agent = OutlineAgent()
        agent.run(sector, region)
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
